import type { JourneyRound, JourneyWorld } from "./types";

export const JOURNEY_WORLDS: JourneyWorld[] = [
  { id: 1, slug: "listening-land", title: "Listening Land", shortTitle: "Listen", icon: "🔊", unlocked: true },
  { id: 2, slug: "word-world", title: "Word World", shortTitle: "Words", icon: "🧸", unlocked: true },
  { id: 3, slug: "sound-garden", title: "Sound & Rhyme Garden", shortTitle: "Sounds", icon: "🎵", unlocked: true },
  { id: 4, slug: "alphabet-adventure", title: "Alphabet Adventure", shortTitle: "Letters", icon: "Aa", unlocked: true },
  { id: 5, slug: "phonics-forest", title: "Phonics Forest", shortTitle: "Phonics", icon: "🌿", unlocked: true },
  { id: 6, slug: "first-words", title: "First Words", shortTitle: "Read", icon: "📖", unlocked: false },
  { id: 7, slug: "spelling-lab", title: "Spelling Lab", shortTitle: "Spell", icon: "🧩", unlocked: false },
  { id: 8, slug: "writing-world", title: "Writing World", shortTitle: "Write", icon: "✏️", unlocked: false },
  { id: 9, slug: "sentence-city", title: "Sentence City", shortTitle: "Sentence", icon: "🏙️", unlocked: false },
  { id: 10, slug: "talk-with-kichu", title: "Talk with Kichu", shortTitle: "Speak", icon: "💬", unlocked: false },
  { id: 11, slug: "story-island", title: "Story Island", shortTitle: "Story", icon: "🏝️", unlocked: false },
  { id: 12, slug: "poem-park", title: "Rhyme & Poem Park", shortTitle: "Poems", icon: "🌈", unlocked: false },
  { id: 13, slug: "reading-adventure", title: "Reading Adventure", shortTitle: "Adventure", icon: "🗺️", unlocked: false },
  { id: 14, slug: "comprehension-quest", title: "Comprehension Quest", shortTitle: "Understand", icon: "🔎", unlocked: false },
  { id: 15, slug: "creative-writing", title: "Creative Writing", shortTitle: "Create", icon: "✨", unlocked: false },
  { id: 16, slug: "real-life-english", title: "Real-Life English", shortTitle: "Use", icon: "🌍", unlocked: false },
];

export const STARTER_MISSION: JourneyRound[] = [
  {
    id: "listen-apple",
    world: 1,
    skill: "Listening",
    prompt: "Tap apple",
    spokenPrompt: "Tap the apple.",
    choices: [
      { id: "apple", label: "Apple", visual: "🍎" },
      { id: "ball", label: "Ball", visual: "⚽" },
      { id: "cat", label: "Cat", visual: "🐱" },
    ],
    correctId: "apple",
    reinforcement: "Apple!",
  },
  {
    id: "listen-dog",
    world: 1,
    skill: "Listening",
    prompt: "Find dog",
    spokenPrompt: "Find the dog.",
    choices: [
      { id: "fish", label: "Fish", visual: "🐟" },
      { id: "dog", label: "Dog", visual: "🐶" },
      { id: "sun", label: "Sun", visual: "☀️" },
    ],
    correctId: "dog",
    reinforcement: "Dog!",
  },
  {
    id: "word-ball",
    world: 2,
    skill: "Vocabulary",
    prompt: "Find ball",
    spokenPrompt: "Find the ball.",
    choices: [
      { id: "book", label: "Book", visual: "📘" },
      { id: "ball", label: "Ball", visual: "⚽" },
      { id: "car", label: "Car", visual: "🚗" },
    ],
    correctId: "ball",
    reinforcement: "Ball!",
  },
  {
    id: "rhyme-hat",
    world: 3,
    skill: "Rhyme",
    prompt: "Cat + ?",
    spokenPrompt: "Which word rhymes with cat? Hat.",
    choices: [
      { id: "hat", label: "Hat", visual: "🎩" },
      { id: "dog", label: "Dog", visual: "🐶" },
      { id: "sun", label: "Sun", visual: "☀️" },
    ],
    correctId: "hat",
    reinforcement: "Cat, hat. They rhyme!",
  },
  {
    id: "letter-m",
    world: 4,
    skill: "Letter recognition",
    prompt: "Find M",
    spokenPrompt: "Find the letter M.",
    choices: [
      { id: "N", label: "N", visual: "N" },
      { id: "M", label: "M", visual: "M" },
      { id: "W", label: "W", visual: "W" },
    ],
    correctId: "M",
    reinforcement: "M!",
  },
  {
    id: "phonics-s",
    world: 5,
    skill: "Letter sound",
    prompt: "Find /s/",
    spokenPrompt: "Find the letter for the sound sss.",
    choices: [
      { id: "S", label: "S", visual: "S" },
      { id: "M", label: "M", visual: "M" },
      { id: "F", label: "F", visual: "F" },
    ],
    correctId: "S",
    reinforcement: "S says sss.",
  },
  {
    id: "little-a",
    world: 4,
    skill: "Upper and lowercase",
    prompt: "Find little a",
    spokenPrompt: "Find little a.",
    choices: [
      { id: "a", label: "Lowercase a", visual: "a" },
      { id: "d", label: "Lowercase d", visual: "d" },
      { id: "o", label: "Lowercase o", visual: "o" },
    ],
    correctId: "a",
    reinforcement: "A and a.",
  },
  {
    id: "follow-red-star",
    world: 1,
    skill: "Listening directions",
    prompt: "Red star",
    spokenPrompt: "Tap the red star.",
    choices: [
      { id: "red-star", label: "Red star", visual: "★", tone: "red" },
      { id: "blue-circle", label: "Blue circle", visual: "●", tone: "blue" },
      { id: "yellow-square", label: "Yellow square", visual: "■", tone: "yellow" },
    ],
    correctId: "red-star",
    reinforcement: "Great listening!",
  },
];
