export type World = "reading" | "writing" | "maths";
export type Mechanic =
  | "choice"
  | "order"
  | "trace"
  | "copy"
  | "start"
  | "build"
  | "line";
export type Game = {
  id: string;
  slug: string;
  title: string;
  world: World;
  skill: string;
  description: string;
  badge: string;
};
export const WORLDS: {
  id: World;
  title: string;
  symbol: string;
  description: string;
  color: string;
}[] = [
  {
    id: "reading",
    title: "Reading Adventure",
    symbol: "Aa",
    description: "From little sounds to stories of your own.",
    color: "#e8dff5",
  },
  {
    id: "writing",
    title: "Writing Adventure",
    symbol: "✎",
    description: "Follow a path. Make a mark. Find your words.",
    color: "#fae8ca",
  },
  {
    id: "maths",
    title: "Maths Adventure",
    symbol: "123",
    description: "Touch, count, build and discover numbers.",
    color: "#dcebdd",
  },
];
export const GAMES: Game[] = [
  [
    "R01",
    "sound-hunter",
    "Sound Hunter",
    "reading",
    "letter-sounds",
    "Listen for a sound and find its letter.",
    "Sound Explorer",
  ],
  [
    "R02",
    "letter-detective",
    "Letter Detective",
    "reading",
    "letter-recognition",
    "Find letters hiding in the meadow.",
    "Letter Detective",
  ],
  [
    "R03",
    "sound-to-picture",
    "Sound to Picture",
    "reading",
    "beginning-sounds",
    "Give each beginning sound a picture friend.",
    "Picture Listener",
  ],
  [
    "R04",
    "first-sound-detective",
    "First Sound Detective",
    "reading",
    "beginning-sounds",
    "Discover the first sound inside a word.",
    "Sound Finder",
  ],
  [
    "R05",
    "confusing-letters",
    "Confusing Letters",
    "reading",
    "letter-recognition",
    "Look closely at letter shapes, one pair at a time.",
    "Careful Observer",
  ],
  [
    "R06",
    "blend-the-sounds",
    "Blend the Sounds",
    "reading",
    "blending",
    "Put spoken sounds together to discover a word.",
    "Sound Blender",
  ],
  [
    "R07",
    "build-the-word",
    "Build the Word",
    "reading",
    "spelling",
    "Put letter tiles in order to build a picture’s name.",
    "Word Builder",
  ],
  [
    "R08",
    "missing-sound",
    "Missing Sound",
    "reading",
    "decoding",
    "Find the missing letter inside a short word.",
    "Word Restorer",
  ],
  [
    "R09",
    "word-picture-match",
    "Word & Picture Match",
    "reading",
    "decoding",
    "Read a little word and find its picture.",
    "Word Explorer",
  ],
  [
    "R10",
    "listen-and-find",
    "Listen & Find",
    "reading",
    "decoding",
    "Listen carefully and choose the matching word.",
    "Word Listener",
  ],
  [
    "R11",
    "sentence-builder",
    "Sentence Builder",
    "reading",
    "sentences",
    "Arrange a few words to make a sentence.",
    "Sentence Builder",
  ],
  [
    "R12",
    "reading-adventure",
    "Reading Adventure",
    "reading",
    "comprehension",
    "Explore sounds, words and tiny stories.",
    "Reading Adventurer",
  ],
  [
    "W01",
    "finger-path",
    "Finger Path",
    "writing",
    "prewriting",
    "Follow lines, curves and winding paths.",
    "Path Explorer",
  ],
  [
    "W02",
    "shape-trace",
    "Shape Trace",
    "writing",
    "prewriting",
    "Draw a circle, square and triangle.",
    "Shape Maker",
  ],
  [
    "W03",
    "letter-road",
    "Letter Road",
    "writing",
    "formation",
    "Travel along each letter’s road in order.",
    "Road Explorer",
  ],
  [
    "W04",
    "trace-the-letter",
    "Trace the Letter",
    "writing",
    "formation",
    "Trace a letter as its guide gently fades.",
    "Letter Maker",
  ],
  [
    "W05",
    "start-point",
    "Start Point",
    "writing",
    "formation",
    "Find where the first pen stroke begins.",
    "Ready to Write",
  ],
  [
    "W06",
    "copy-the-letter",
    "Copy the Letter",
    "writing",
    "independent-writing",
    "Look at a letter and make your own version.",
    "Independent Writer",
  ],
  [
    "W07",
    "complete-the-letter",
    "Complete the Letter",
    "writing",
    "formation",
    "Finish a letter’s missing stroke.",
    "Letter Restorer",
  ],
  [
    "W08",
    "writing-build-the-word",
    "Build & Write a Word",
    "writing",
    "word-writing",
    "Build a word, then practise its letter shapes.",
    "Writing Star",
  ],
  [
    "W09",
    "hear-and-spell",
    "Hear & Spell",
    "writing",
    "spelling",
    "Hear a word and put its letters in order.",
    "Spelling Explorer",
  ],
  [
    "W10",
    "my-name",
    "My Name",
    "writing",
    "personal-writing",
    "Recognise, build and practise your own name.",
    "My Name Maker",
  ],
  [
    "M01",
    "quantity-sense",
    "Quantity Sense",
    "maths",
    "quantity",
    "Find a group by how many objects it contains.",
    "Quantity Explorer",
  ],
  [
    "M02",
    "number-match",
    "Number Match",
    "maths",
    "number-symbols",
    "Help a group of objects find its number.",
    "Number Matcher",
  ],
  [
    "M03",
    "number-sound",
    "Number & Sound",
    "maths",
    "number-symbols",
    "Listen to a number and find it.",
    "Number Listener",
  ],
  [
    "M04",
    "number-builder",
    "Number Builder",
    "maths",
    "quantity",
    "Build a group, one object at a time.",
    "Number Builder",
  ],
  [
    "M05",
    "more-or-less",
    "More or Less",
    "maths",
    "comparison",
    "Compare groups and find more or fewer.",
    "Group Explorer",
  ],
  [
    "M06",
    "number-line-adventure",
    "Number Line Adventure",
    "maths",
    "number-line",
    "Take small jumps along a number line.",
    "Number Traveller",
  ],
  [
    "M07",
    "missing-number",
    "Missing Number",
    "maths",
    "sequence",
    "Restore the missing number in a trail.",
    "Sequence Finder",
  ],
  [
    "M08",
    "make-five",
    "Make 5",
    "maths",
    "number-bonds",
    "Add objects to complete a group of five.",
    "Five Maker",
  ],
  [
    "M09",
    "addition-story",
    "Addition Story",
    "maths",
    "addition",
    "Bring groups together and count the new group.",
    "Story Counter",
  ],
  [
    "M10",
    "take-away",
    "Take Away",
    "maths",
    "subtraction",
    "Take some objects away and count what remains.",
    "Number Thinker",
  ],
  [
    "M11",
    "maths-shop",
    "Maths Shop",
    "maths",
    "money",
    "Practise paying with pretend rupee coins.",
    "Everyday Explorer",
  ],
  [
    "M12",
    "maths-adventure",
    "Maths Adventure",
    "maths",
    "maths-transfer",
    "Explore groups, number trails and little maths stories.",
    "Maths Adventurer",
  ],
].map(([id, slug, title, world, skill, description, badge]) => ({
  id,
  slug,
  title,
  world: world as World,
  skill,
  description,
  badge,
}));
export const SKILLS: Record<
  World,
  { id: string; title: string; prerequisite?: string }[]
> = {
  reading: [
    ["letter-recognition", "Letter recognition"],
    ["letter-sounds", "Letter sounds"],
    ["beginning-sounds", "Beginning sounds"],
    ["blending", "Sound blending"],
    ["decoding", "Simple words"],
    ["spelling", "Spelling"],
    ["sentences", "Simple sentences"],
    ["comprehension", "Reading comprehension"],
  ].map(([id, title], i, a) => ({ id, title, prerequisite: a[i - 1]?.[0] })),
  writing: [
    ["prewriting", "Paths & shapes"],
    ["formation", "Letter formation"],
    ["independent-writing", "Independent letters"],
    ["word-writing", "Word writing"],
    ["spelling", "Spelling"],
    ["personal-writing", "Meaningful writing"],
  ].map(([id, title], i, a) => ({ id, title, prerequisite: a[i - 1]?.[0] })),
  maths: [
    ["quantity", "Quantity"],
    ["number-symbols", "Number symbols"],
    ["comparison", "More & fewer"],
    ["sequence", "Number order"],
    ["number-line", "Number line"],
    ["number-bonds", "Number relationships"],
    ["addition", "Addition"],
    ["subtraction", "Subtraction"],
    ["money", "Everyday maths"],
    ["maths-transfer", "Using maths"],
  ].map(([id, title], i, a) => ({ id, title, prerequisite: a[i - 1]?.[0] })),
};
export const gameBySlug = (slug: string) => GAMES.find((g) => g.slug === slug);
export const CONTENT_VERSION = "world-1.0";
// Curated short-vowel CVC set. CAT uses hard C; no untaught long vowels or digraphs.
export const WORDS = [
  { word: "cat", picture: "C", sounds: "/k/ /a/ /t/" },
  { word: "dog", picture: "D", sounds: "/d/ /o/ /g/" },
  { word: "sun", picture: "S", sounds: "/s/ /u/ /n/" },
  { word: "hat", picture: "H", sounds: "/h/ /a/ /t/" },
  { word: "van", picture: "V", sounds: "/v/ /a/ /n/" },
  { word: "jam", picture: "J", sounds: "/j/ /a/ /m/" },
];
export const TEACHING_SEQUENCE = [
  "A",
  "M",
  "S",
  "B",
  "F",
  "T",
  "C",
  "L",
  "P",
  "D",
  "N",
  "H",
  "I",
  "G",
  "O",
  "U",
  "V",
  "J",
  "E",
  "R",
  "W",
  "K",
  "Y",
  "Z",
  "Q",
  "X",
];
