import type { MathsRound, MathsWorld } from "./types";

export const MATHS_WORLDS: MathsWorld[] = [
  { id: 1, slug: "look-and-match", title: "Look & Match", shortTitle: "Match", icon: "◉", unlocked: true },
  { id: 2, slug: "quantity-island", title: "Quantity Island", shortTitle: "How many?", icon: "●●", unlocked: true },
  { id: 3, slug: "counting-trail", title: "Counting Trail", shortTitle: "Count", icon: "123", unlocked: true },
  { id: 4, slug: "number-symbols", title: "Number Symbols", shortTitle: "Numbers", icon: "4", unlocked: true },
  { id: 5, slug: "compare-cove", title: "Compare Cove", shortTitle: "More", icon: "↔", unlocked: true },
  { id: 6, slug: "order-road", title: "Order Road", shortTitle: "Order", icon: "1·2·3", unlocked: true },
  { id: 7, slug: "number-line-valley", title: "Number Line Valley", shortTitle: "Line", icon: "—●—", unlocked: true },
  { id: 8, slug: "make-and-break", title: "Make & Break Numbers", shortTitle: "Make", icon: "2+3", unlocked: true },
  { id: 9, slug: "addition-village", title: "Addition Village", shortTitle: "Add", icon: "+", unlocked: true },
  { id: 10, slug: "subtraction-river", title: "Subtraction River", shortTitle: "Take away", icon: "−", unlocked: true },
  { id: 11, slug: "pattern-planet", title: "Pattern Planet", shortTitle: "Patterns", icon: "◆◇", unlocked: false },
  { id: 12, slug: "shape-city", title: "Shape City", shortTitle: "Shapes", icon: "△□", unlocked: false },
  { id: 13, slug: "measure-lab", title: "Measure Lab", shortTitle: "Measure", icon: "↕", unlocked: false },
  { id: 14, slug: "time-town", title: "Time Town", shortTitle: "Time", icon: "◷", unlocked: false },
  { id: 15, slug: "money-market", title: "Money Market", shortTitle: "Money", icon: "₹", unlocked: false },
  { id: 16, slug: "groups-and-sharing", title: "Groups & Sharing", shortTitle: "Groups", icon: "×÷", unlocked: false },
  { id: 17, slug: "fraction-picnic", title: "Fraction Picnic", shortTitle: "Parts", icon: "½", unlocked: false },
  { id: 18, slug: "real-life-maths", title: "Real-Life Maths", shortTitle: "Use maths", icon: "★", unlocked: false },
];

export const STARTER_MATHS_MISSION: MathsRound[] = [
  {
    id: "quantity-three",
    world: 2,
    skill: "Quantity",
    prompt: "How many?",
    spokenPrompt: "How many dots? Touch the answer.",
    visualType: "objects",
    visualValue: 3,
    choices: [
      { id: "2", label: "Two", value: "2" },
      { id: "3", label: "Three", value: "3" },
      { id: "4", label: "Four", value: "4" },
    ],
    correctId: "3",
    reinforcement: "Three!",
  },
  {
    id: "count-four",
    world: 3,
    skill: "Counting",
    prompt: "Count them",
    spokenPrompt: "Count the stars. How many?",
    visualType: "objects",
    visualValue: 4,
    choices: [
      { id: "3", label: "Three", value: "3" },
      { id: "4", label: "Four", value: "4" },
      { id: "5", label: "Five", value: "5" },
    ],
    correctId: "4",
    reinforcement: "One, two, three, four. Four!",
  },
  {
    id: "number-five",
    world: 4,
    skill: "Number symbol",
    prompt: "Find 5",
    spokenPrompt: "Find number five.",
    visualType: "number",
    visualValue: 5,
    choices: [
      { id: "2", label: "Two", value: "2" },
      { id: "5", label: "Five", value: "5" },
      { id: "8", label: "Eight", value: "8" },
    ],
    correctId: "5",
    reinforcement: "Five!",
  },
  {
    id: "more-group",
    world: 5,
    skill: "Comparison",
    prompt: "Which has more?",
    spokenPrompt: "Which group has more?",
    visualType: "compare",
    visualValue: [2, 5],
    choices: [
      { id: "left", label: "Two dots", value: "2", count: 2 },
      { id: "right", label: "Five dots", value: "5", count: 5 },
    ],
    correctId: "right",
    reinforcement: "Five is more than two.",
  },
  {
    id: "missing-three",
    world: 6,
    skill: "Number order",
    prompt: "2 · ? · 4",
    spokenPrompt: "Two, blank, four. What number is missing?",
    visualType: "sequence",
    visualValue: [2, 0, 4],
    choices: [
      { id: "1", label: "One", value: "1" },
      { id: "3", label: "Three", value: "3" },
      { id: "5", label: "Five", value: "5" },
    ],
    correctId: "3",
    reinforcement: "Two, three, four.",
  },
  {
    id: "line-six",
    world: 7,
    skill: "Number line",
    prompt: "Find 6",
    spokenPrompt: "Find six on the number line.",
    visualType: "number-line",
    visualValue: [3, 4, 5, 6, 7],
    choices: [
      { id: "5", label: "Five", value: "5" },
      { id: "6", label: "Six", value: "6" },
      { id: "7", label: "Seven", value: "7" },
    ],
    correctId: "6",
    reinforcement: "Six!",
  },
  {
    id: "make-five",
    world: 8,
    skill: "Number bonds",
    prompt: "3 + ? = 5",
    spokenPrompt: "Three and how many more make five?",
    visualType: "equation",
    visualValue: "3 + ? = 5",
    choices: [
      { id: "1", label: "One", value: "1" },
      { id: "2", label: "Two", value: "2" },
      { id: "3", label: "Three", value: "3" },
    ],
    correctId: "2",
    reinforcement: "Three and two make five!",
  },
  {
    id: "add-two-one",
    world: 9,
    skill: "Addition",
    prompt: "2 + 1 = ?",
    spokenPrompt: "Two plus one. How many altogether?",
    visualType: "equation",
    visualValue: "2 + 1 = ?",
    choices: [
      { id: "2", label: "Two", value: "2" },
      { id: "3", label: "Three", value: "3" },
      { id: "4", label: "Four", value: "4" },
    ],
    correctId: "3",
    reinforcement: "Two plus one is three.",
  },
  {
    id: "take-one",
    world: 10,
    skill: "Subtraction",
    prompt: "4 − 1 = ?",
    spokenPrompt: "Four take away one. How many are left?",
    visualType: "equation",
    visualValue: "4 − 1 = ?",
    choices: [
      { id: "2", label: "Two", value: "2" },
      { id: "3", label: "Three", value: "3" },
      { id: "4", label: "Four", value: "4" },
    ],
    correctId: "3",
    reinforcement: "Four take away one leaves three.",
  },
  {
    id: "rupee-five",
    world: 15,
    skill: "Money",
    prompt: "Find ₹5",
    spokenPrompt: "Find five rupees.",
    visualType: "money",
    visualValue: "₹5",
    choices: [
      { id: "2", label: "Two rupees", value: "₹2" },
      { id: "5", label: "Five rupees", value: "₹5" },
      { id: "10", label: "Ten rupees", value: "₹10" },
    ],
    correctId: "5",
    reinforcement: "Five rupees.",
  },
];
