import Link from 'next/link';
import { GuideCharacter, Icon } from '../english/Art';
import { primary, secondary } from '../english/Controls';
import { LEVELS } from '../../lib/sound-match/content';
import type { Progress } from '../../lib/sound-match/types';
import { SoundGarden } from './SoundArt';
export function SoundHome({ progress:p,onStart,onTutorial,onParents }: { progress:Progress;onStart:(level:number)=>void;onTutorial:()=>void;onParents:()=>void }) {
  return <section className="sound-match-home mx-auto w-full min-w-0 max-w-5xl overflow-x-hidden"><Link href="/" className="mb-4 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-primary"><Icon name="back"/>All games</Link><div className="sound-match-home-hero overflow-hidden rounded-[36px] border border-border bg-white shadow-sm"><div className="sound-match-home-hero-inner grid items-center gap-4 p-6 sm:grid-cols-[1fr_auto] sm:p-10"><div><p className="text-xs font-black uppercase tracking-[.2em] text-primary">Game 02 · The Sound Garden</p><h1 className="m-0 text-4xl font-black tracking-tight text-primary-dark sm:text-6xl">Sound Match</h1><p className="max-w-sm text-lg leading-relaxed text-muted">Listen and find the matching sound!</p><div className="flex flex-wrap gap-3"><button className={primary} onClick={()=>onStart(p.session?.level??p.highestUnlockedLevel)}>{p.session?'Continue':'Play'}<Icon name="play"/></button><button className={secondary} onClick={onTutorial}>How to play</button></div></div><GuideCharacter mood="listening" className="mx-auto w-32 sm:w-44"/></div><SoundGarden current={p.completedLevels.length}/></div><div className="mb-4 mt-8 flex flex-wrap items-center justify-between gap-2"><h2 className="text-xl font-extrabold">Six places to discover</h2><span className="text-xs font-bold text-muted">A little listening, at your pace</span></div><div className="sound-match-level-grid grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{LEVELS.map((l,i)=>{const level=i+1,locked=level>p.highestUnlockedLevel,done=p.completedLevels.includes(level);return <button key={l.title} aria-label={`Level ${level}: ${l.title}${locked?', locked':''}`} disabled={locked} onClick={()=>onStart(level)} className="flex min-h-36 items-start gap-4 rounded-3xl border border-border bg-white p-5 text-left transition enabled:hover:bg-surface-soft disabled:bg-[#f2eee8] disabled:opacity-65"><span className={`grid size-10 shrink-0 place-items-center rounded-full ${done?'bg-[#f5df9f] text-[#92712b]':'bg-[#eee8f6] text-primary'}`}>{done?<Icon name="star"/>:locked?<Icon name="lock"/>:<span className="font-black">{level}</span>}</span><span><span className="block text-xs font-bold uppercase tracking-wider text-primary">{l.area}</span><span className="mt-2 block text-base font-extrabold">{l.title}</span><span className="mt-2 block text-xs leading-relaxed text-muted">{locked?'A new place after the one before.':l.description}</span></span></button>;})}</div><button className="mx-auto mt-6 block min-h-11 px-5 text-sm font-bold text-muted" onClick={onParents}>For grown-ups</button></section>;
}
